tosca_definitions_version: tosca_simple_yaml_1_0

topology_template:
  node_templates:
    my-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: localhost
        public_address: localhost

    hello:
      type: tosca.nodes.SoftwareComponent
      requirements:
        - host: my-workstation
      interfaces:
        Standard:
          create: playbooks/hello/create.yml