---
tosca_definitions_version: tosca_simple_yaml_1_3

imports:
  - modules/docker/docker.yml
  - modules/minio/minio.yml
  - modules/openfaas/openfaas.yml

topology_template:
  inputs:
    host_ip:
      type: string
    credentials:
      type: string
    linux_distro:
      type: string
    linux_release:
      type: string

  node_templates:
    my-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: { get_input: host_ip }
        public_address: { get_input: host_ip }

    docker_setup:
      type: radon.nodes.docker_setup
      properties:
        linux_distro: { get_input: linux_distro }
        linux_release: { get_input: linux_release }
      requirements:
        - host: my-workstation

    openfaas:
      type: radon.nodes.openfaas
      requirements:
        - host: my-workstation

    minio_object_storage:
      type: radon.nodes.minio
      properties:
        minio_ip: { get_input: host_ip }
        credentials: { get_input: credentials }
      requirements:
        - host: my-workstation
...
