tosca_definitions_version: tosca_simple_yaml_1_0

node_types:
  my.nodes.MockComponent:
    derived_from: tosca.nodes.SoftwareComponent
    properties:
      path:
        type: string
        description: Path on the host where this "component" resides
    attributes:
      id:
        type: string
        description: Unique ID of the "server"

  my.nodes.MockServer:
    derived_from: my.nodes.MockComponent
    capabilities:
      server:
        type: tosca.capabilities.Node
        valid_source_types: [my.nodes.MockComponent]
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        create:
          inputs:
            path: { default: { get_property: [SELF, path] } }
          implementation: playbooks/mock-server/create.yml

  my.nodes.MockClient:
    derived_from: my.nodes.MockComponent
    requirements:
      - server:
          capability: tosca.capabilities.Node
          relationship: my.relationships.MockServerClient
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        inputs:
          path: { default: { get_property: [SELF, path] } }
        create:
          implementation: playbooks/mock-client/create.yml
        configure:
          inputs:
            server_id: { default: { get_attribute: [ SELF, server, id ] } }
          implementation: playbooks/mock-client/configure.yml

relationship_types:
  my.relationships.MockServerClient:
    derived_from: tosca.relationships.DependsOn
    valid_target_types: [my.nodes.MockServer]

topology_template:
  node_templates:
    my-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: localhost
        public_address: localhost

    my-mock-server:
      type: my.nodes.MockServer
      properties:
        path: /tmp/playing-opera/02/server
      requirements:
        - host: my-workstation

    my-mock-client:
      type: my.nodes.MockClient
      properties:
        path: /tmp/playing-opera/02/client
      requirements:
        - host: my-workstation
        - server: my-mock-server
